model:
  vocab_size: 512
  context_length: 256
  d_model: 256
  n_heads: 8
  d_ff: 1024
  dropout: 0.1
  bias: true
  layer_norm_epsilon: 0.00001
  n_layers: 6
  initializer_range: 0.02
  tie_embeddings: true
