model:
  vocab_size: 320
  context_length: 128
  d_model: 128
  n_heads: 4
  d_ff: 512
  dropout: 0.1
  bias: true
  layer_norm_epsilon: 0.00001
  n_layers: 4
  initializer_range: 0.02
  tie_embeddings: true
